from fastapi_pagination import Page
from sqlalchemy.ext.asyncio import AsyncSession
from fastapi_pagination.ext.sqlalchemy import paginate
from backend.api.schemas.user import User
from sqlalchemy import select


class UserRepository:
    async def add_new_user(self, user: User, session: AsyncSession) -> User:
        """
        Add a new user to the database.

        :param user: the User object to be added to the database, containing the user's email, hashed password, and role
        :param session: an AsyncSession object that provides a database session for performing the database operation to add the new user to the database

        :return: the User object that was added to the database, which may include additional fields such as the user's id that was generated by the database upon insertion
        """
        session.add(user)
        return user

    async def find_user_by_email(
        self, email: str, session: AsyncSession
    ) -> User | None:
        """
        Find a user in the database by their email address.

        :param email: the email address of the user to be found in the database, which is used as a unique identifier for the user
        :param session: an AsyncSession object that provides a database session for performing the database operation to find the user in the database based on their email address

        :return: the User object that matches the given email address if found in the database, or None if no user with the specified email address exists in the database
        """

        statement = select(User).where(User.email == email)

        optional_user = await session.execute(statement)
        user = optional_user.scalar_one_or_none()
        return user

    async def get_all_users(self, session: AsyncSession, page_params) -> Page[User]:
        """
        get a list of all users in the database with pagination support.

        :param session: an AsyncSession object that provides a database session for performing the database operation to retrieve all users from the
        :param page_params: pagination parameters that specify the page number and page size for retrieving the list of users from the database, allowing for efficient retrieval of large datasets by returning only a subset of the total results based on the specified pagination parameters

        :return: a Page object containing a list of User entities representing the users retrieved from the database, along with pagination metadata such as total number of users, total number of pages, and current page information
        """

        statement = select(User)
        return await paginate(session, statement, page_params)
